export interface AchievementDef {
  id: string
  name: string
  description: string
  icon: string
  badge_color: string
  category: 'Streak' | 'Total Days' | 'Category' | 'Journal' | 'Consistency' | 'Explorer' | 'Early Bird' | 'Night Owl' | 'Resource' | 'Milestones'
  requirement_type: 'streak' | 'total_days' | 'categories_count' | 'journal_count' | 'perfect_week' | 'perfect_month' | 'explorer' | 'early_bird' | 'night_owl' | 'resource_count' | 'milestone'
  requirement_value: number
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary'
}

export const RARITY_COLORS: Record<AchievementDef['rarity'], { bg: string; border: string; text: string; hex: string }> = {
  Common: { bg: 'bg-gray-500/10', border: 'border-gray-500/30', text: 'text-gray-400', hex: '#9ca3af' },
  Uncommon: { bg: 'bg-emerald-500/10', border: 'border-emerald-500/30', text: 'text-emerald-500', hex: '#22c55e' },
  Rare: { bg: 'bg-blue-500/10', border: 'border-blue-500/30', text: 'text-blue-500', hex: '#3b82f6' },
  Epic: { bg: 'bg-purple-500/10', border: 'border-purple-500/30', text: 'text-purple-500', hex: '#a855f7' },
  Legendary: { bg: 'bg-amber-500/10', border: 'border-amber-500/30', text: 'text-amber-500', hex: '#f59e0b' },
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDef[] = [
  // 1. Streak Achievements
  {
    id: 'first_step',
    name: 'First Step',
    description: 'Complete your first day.',
    icon: 'Flame',
    badge_color: '#9ca3af',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 1,
    rarity: 'Common',
  },
  {
    id: 'streak_3',
    name: '3 Day Streak',
    description: 'Maintain a 3-day streak.',
    icon: 'Flame',
    badge_color: '#22c55e',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 3,
    rarity: 'Uncommon',
  },
  {
    id: 'streak_7',
    name: '7 Day Streak',
    description: 'Maintain a 7-day streak.',
    icon: 'Flame',
    badge_color: '#3b82f6',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 7,
    rarity: 'Rare',
  },
  {
    id: 'streak_14',
    name: '14 Day Streak',
    description: 'Maintain a 14-day streak.',
    icon: 'Flame',
    badge_color: '#3b82f6',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 14,
    rarity: 'Rare',
  },
  {
    id: 'streak_30',
    name: '30 Day Streak',
    description: 'Maintain a 30-day streak.',
    icon: 'Flame',
    badge_color: '#a855f7',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 30,
    rarity: 'Epic',
  },
  {
    id: 'streak_50',
    name: '50 Day Streak',
    description: 'Maintain a 50-day streak.',
    icon: 'Flame',
    badge_color: '#a855f7',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 50,
    rarity: 'Epic',
  },
  {
    id: 'streak_100',
    name: '100 Day Streak',
    description: 'Maintain a 100-day streak.',
    icon: 'Flame',
    badge_color: '#f59e0b',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 100,
    rarity: 'Legendary',
  },
  {
    id: 'streak_365',
    name: '365 Day Streak',
    description: 'Maintain a 365-day streak.',
    icon: 'Flame',
    badge_color: '#f59e0b',
    category: 'Streak',
    requirement_type: 'streak',
    requirement_value: 365,
    rarity: 'Legendary',
  },

  // 2. Total Completed Days
  {
    id: 'days_10',
    name: '10 Days Completed',
    description: 'Complete 10 unique days.',
    icon: 'CalendarDays',
    badge_color: '#9ca3af',
    category: 'Total Days',
    requirement_type: 'total_days',
    requirement_value: 10,
    rarity: 'Common',
  },
  {
    id: 'days_25',
    name: '25 Days Completed',
    description: 'Complete 25 unique days.',
    icon: 'CalendarDays',
    badge_color: '#22c55e',
    category: 'Total Days',
    requirement_type: 'total_days',
    requirement_value: 25,
    rarity: 'Uncommon',
  },
  {
    id: 'days_50',
    name: '50 Days Completed',
    description: 'Complete 50 unique days.',
    icon: 'CalendarDays',
    badge_color: '#3b82f6',
    category: 'Total Days',
    requirement_type: 'total_days',
    requirement_value: 50,
    rarity: 'Rare',
  },
  {
    id: 'days_100',
    name: '100 Days Completed',
    description: 'Complete 100 unique days.',
    icon: 'CalendarDays',
    badge_color: '#a855f7',
    category: 'Total Days',
    requirement_type: 'total_days',
    requirement_value: 100,
    rarity: 'Epic',
  },
  {
    id: 'days_250',
    name: '250 Days Completed',
    description: 'Complete 250 unique days.',
    icon: 'CalendarDays',
    badge_color: '#f59e0b',
    category: 'Total Days',
    requirement_type: 'total_days',
    requirement_value: 250,
    rarity: 'Legendary',
  },
  {
    id: 'days_500',
    name: '500 Days Completed',
    description: 'Complete 500 unique days.',
    icon: 'CalendarDays',
    badge_color: '#f59e0b',
    category: 'Total Days',
    requirement_type: 'total_days',
    requirement_value: 500,
    rarity: 'Legendary',
  },

  // 3. Category Achievements
  {
    id: 'cat_1',
    name: 'Create First Category',
    description: 'Create your first category.',
    icon: 'FolderPlus',
    badge_color: '#9ca3af',
    category: 'Category',
    requirement_type: 'categories_count',
    requirement_value: 1,
    rarity: 'Common',
  },
  {
    id: 'cat_5',
    name: 'Create 5 Categories',
    description: 'Create 5 tracking categories.',
    icon: 'Layers',
    badge_color: '#22c55e',
    category: 'Category',
    requirement_type: 'categories_count',
    requirement_value: 5,
    rarity: 'Uncommon',
  },
  {
    id: 'cat_10',
    name: 'Create 10 Categories',
    description: 'Create 10 tracking categories.',
    icon: 'Grid',
    badge_color: '#3b82f6',
    category: 'Category',
    requirement_type: 'categories_count',
    requirement_value: 10,
    rarity: 'Rare',
  },

  // 4. Journal Achievements
  {
    id: 'journal_1',
    name: 'First Journal Entry',
    description: 'Write your first journal entry.',
    icon: 'PenTool',
    badge_color: '#9ca3af',
    category: 'Journal',
    requirement_type: 'journal_count',
    requirement_value: 1,
    rarity: 'Common',
  },
  {
    id: 'journal_25',
    name: '25 Journal Entries',
    description: 'Write 25 journal entries.',
    icon: 'BookOpen',
    badge_color: '#22c55e',
    category: 'Journal',
    requirement_type: 'journal_count',
    requirement_value: 25,
    rarity: 'Uncommon',
  },
  {
    id: 'journal_100',
    name: '100 Journal Entries',
    description: 'Write 100 journal entries.',
    icon: 'Feather',
    badge_color: '#a855f7',
    category: 'Journal',
    requirement_type: 'journal_count',
    requirement_value: 100,
    rarity: 'Epic',
  },

  // 5. Consistency Achievements
  {
    id: 'perfect_week',
    name: 'Perfect Week',
    description: 'Complete every day for 7 consecutive days.',
    icon: 'Star',
    badge_color: '#3b82f6',
    category: 'Consistency',
    requirement_type: 'perfect_week',
    requirement_value: 7,
    rarity: 'Rare',
  },
  {
    id: 'perfect_month',
    name: 'Perfect Month',
    description: 'Complete every day for 30 consecutive days.',
    icon: 'Trophy',
    badge_color: '#a855f7',
    category: 'Consistency',
    requirement_type: 'perfect_month',
    requirement_value: 30,
    rarity: 'Epic',
  },

  // 6. Explorer
  {
    id: 'explorer_5',
    name: 'Explorer',
    description: 'Complete at least one task in 5 different categories.',
    icon: 'Compass',
    badge_color: '#3b82f6',
    category: 'Explorer',
    requirement_type: 'explorer',
    requirement_value: 5,
    rarity: 'Rare',
  },

  // 7. Early Bird
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Complete a task before 9 AM.',
    icon: 'Sun',
    badge_color: '#22c55e',
    category: 'Early Bird',
    requirement_type: 'early_bird',
    requirement_value: 9,
    rarity: 'Uncommon',
  },

  // 8. Night Owl
  {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Complete a task after 10 PM.',
    icon: 'Moon',
    badge_color: '#22c55e',
    category: 'Night Owl',
    requirement_type: 'night_owl',
    requirement_value: 22,
    rarity: 'Uncommon',
  },

  // 9. Resource Learner
  {
    id: 'resource_25',
    name: 'Resource Learner',
    description: 'Add 25 resource links.',
    icon: 'Link2',
    badge_color: '#3b82f6',
    category: 'Resource',
    requirement_type: 'resource_count',
    requirement_value: 25,
    rarity: 'Rare',
  },

  // 10. Milestones
  {
    id: 'bronze_learner',
    name: 'Bronze Learner',
    description: 'Reach 5 completed days.',
    icon: 'Award',
    badge_color: '#cd7f32',
    category: 'Milestones',
    requirement_type: 'milestone',
    requirement_value: 5,
    rarity: 'Common',
  },
  {
    id: 'silver_learner',
    name: 'Silver Learner',
    description: 'Reach 25 completed days.',
    icon: 'Medal',
    badge_color: '#c0c0c0',
    category: 'Milestones',
    requirement_type: 'milestone',
    requirement_value: 25,
    rarity: 'Uncommon',
  },
  {
    id: 'gold_learner',
    name: 'Gold Learner',
    description: 'Reach 50 completed days.',
    icon: 'Crown',
    badge_color: '#f59e0b',
    category: 'Milestones',
    requirement_type: 'milestone',
    requirement_value: 50,
    rarity: 'Rare',
  },
  {
    id: 'master_learner',
    name: 'Master Learner',
    description: 'Reach 100 completed days.',
    icon: 'Gem',
    badge_color: '#a855f7',
    category: 'Milestones',
    requirement_type: 'milestone',
    requirement_value: 100,
    rarity: 'Epic',
  },
]
